/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"
static void GPIO_LedConfig();
static void LockControl();
static void GPIO_ButtonInterruptConfg();

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static void GPIO_LedConfig();

void EXTI0_IRQHandler()
{
	if ( EXTI->PR & 0x1 )
	{
		EXTI->PR |= ( 0x1U << 0U);

		GPIO_WritePin(GPIOD, GPIO_PIN_All, GPIO_Pin_Set);
	}
}

int main(void)
{

	/**/
	GPIO_LedConfig();



	GPIO_ButtonInterruptConfg();
    /* Loop forever */
	for(;;)
	{
		//GPIO_WritePin(GPIOG,GPIO_PIN_All, GPIO_Pin_Set);
		GPIO_WritePin(GPIOG,GPIO_PIN_All,GPIO_Pin_Reset);
	}

}

static void GPIO_LedConfig()
{
	GPIO_InitTypeDef_t GPIO_InitStruct = {0};

	RCC_GPIOG_CLK_ENABLE();
	RCC_GPIOA_CLK_ENABLE();
	RCC_SYSCFG_CLK_ENABLE();

	GPIO_InitStruct.pinNumber = GPIO_PIN_12 | GPIO_PIN_13 | GPIO_PIN_14 | GPIO_PIN_15;
	GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT;
	GPIO_InitStruct.Speed = GPIO_OSPEED_LOW;
	GPIO_InitStruct.Otype = GPIO_OTYPE_PP;
	GPIO_InitStruct.PuPd = GPIO_PUPD_NOPULL;

	GPIO_Init(GPIOG, &GPIO_InitStruct);

	memset(&GPIO_InitStruct, 0, sizeof(GPIO_InitStruct));

	GPIO_InitStruct.pinNumber = GPIO_PIN_0;
	GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
	GPIO_InitStruct.PuPd = GPIO_PUPD_PULLDOWN; //when button not pressed, port should read 0. otherwise it would read float num. see schematics.
	GPIO_Init(GPIOA, &GPIO_InitStruct);

	//EXTI_LineConfig(EXTI_PortSource_GPIOC,EXTI_Source_14);

}

static void GPIO_ButtonInterruptConfg()
{
	EXTI_InitTypeDef_t EXTI_InitStruct = { 0 };

	RCC_SYSCFG_CLK_ENABLE();

	EXTI_LineConfig(EXTI_PortSource_GPIOA, EXTI_Source_0);

	EXTI_InitStruct.EXTI_LineCmd = ENABLE;
	EXTI_InitStruct.EXTI_LineNumber = EXTI_Source_0;
	EXTI_InitStruct.EXTI_Mode = EXTI_MODE_Interrupt;
	EXTI_InitStruct.TriggerSelection = EXTI_Trigger_Rising;


	EXTI_Init(&EXTI_InitStruct);

	NVIC_EnableInterrupt(EXTI0_IRQNumber);

}
